runtime: python310 # or another supported version

instance_class: F1

env_variables:
  BUCKET_NAME: "where-should-i-go-eat-v2.appspot.com"

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /images
  static_dir: static/img

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
