#!/usr/bin/env python3
restaurant_urls: tuple = (
    ("Applebee's", "https://restaurants.applebees.com/en-us/"),
    ("Arby's", "https://www.arbys.com/locations/"),
    ("Atlanta Bread Company", "https://order.online/business/atlanta-bread-company-24026/?delivery=true"),
    ("Auntie Anne's", "https://order.auntieannes.com/"),
    ("A&W", "https://awrestaurants.com/locations/"),
    ("Back Yard Burgers", "https://www.backyardburgers.com/online-ordering/"),
    ("Baja Fresh", "https://order.bajafresh.com/"),
    ("Benihana", "https://order.benihana.com/"),
    ("Bennigan's", "https://bennigans.alohaorderonline.com/"),
    ("Bj's Restaurants", "https://www.bjsrestaurants.com/locations"),
    ("Blaze Pizza", "https://www.blazepizza.com/order/action/delivery"),
    ("Blimpie", "https://order.blimpie.com/"),
    ("Bob Evans Restaurant", "https://www.bobevans.com/order"),
    ("Bojangles", "https://www.bojangles.com/locations/?order=delivery"),
    ("Bonefish Grill", "https://order.bonefishgrill.com/"),
    ("Boston Market", "https://my.bostonmarket.com/order/action/delivery"),
    ("Buffalo Wild Wings", "https://www.buffalowildwings.com/locations/?backTo=%2F"),
    ("BurgerFi", "https://order.burgerfi.com/locations"),
    ("Burger King", "https://www.bk.com/"),
    ("California Pizza Kitchen", "https://www.cpk.com/locations"),
    ("Captain D's", "https://order.captainds.com/"),
    ("Carl's Jr / Hardee's", "https://www.carlsjr.com/locations"),
    ("Carrabba's Italian Grill","https://order.carrabbas.com/"),
    ("Charleys Philly Steaks", "https://order.charleys.com/"),
    ("Checkers / Rally's", "https://www.checkers.com/order-delivery/"),
    ("Cheddar's", "https://www.cheddars.com/menu/family-bundles"),
    ("Chick-fil-A", "https://order.chick-fil-a.com/delivery/address"),
    ("Chili's", "https://www.chilis.com/locations"),
    ("Chipotle", "https://www.chipotle.com/order/#menu"),
    ("Chuck E. Cheese's", "https://www.chuckecheese.com/"),
    ("Church's Chicken", "https://order.churchs.com/"),
    ("Cicis", "https://order.cicis.com/"),
    ("Cook Out", "https://cookout.com/"),
    ("Cracker Barrel", "https://www.crackerbarrel.com/locations"),
    ("Culver's", "https://www.culvers.com/online-ordering-locator"),
    ("Dave & Busters", "https://daveandbusters.order.online/business/dave-&-buster's-165371/"),
    ("Dairy Queen", "https://www.dairyqueen.com/en-us/order/"),
    ("Del Taco", "https://order.deltaco.com/"),
    ("Denny's", "https://www.dennys.com/order"),
    ("Domino's Pizza", "https://www.dominos.com/en/restaurants?type=Delivery"),
    ("Dunkin", "https://www.dunkindonuts.com/en/dunkin-delivers"),
    ("Einstein Bros. Bagels", "https://locations.einsteinbros.com/index.html"),
    ("El Pollo Loco", "https://order.elpolloloco.com/?delivery=true"),
    ("Fazoli's", "https://order.fazolis.com/"),
    ("Firehouse Subs", "https://order.firehousesubs.com/menu/-101010/subs/20066"),
    ("Freddy's Frozen Custard & Steakburgers", "https://www.freddys.com/order"),
    ("Friendly's", "https://order.friendlysrestaurants.com/"),
    ("Five Guys", "https://order.fiveguys.com/"),
    ("Fogo de Chao", "https://fogodechao.com/reservations/"),
    ("Fox's Pizza Den", "https://foxspizza.arrowpos.com/locator"),
    ("Fuddruckers", "https://order.fuddruckers.com/"),
    ("Golden Corral", "https://www.goldencorral.com/order-online/"),
    ("Hard Rock Cafe", "https://www.hardrockcafe.com/delivery.aspx"),
    ("Hooters", "https://order.hooters.com/"),
    ("Houlihan's", "https://houlihans.com/"),
    ("Huddle House", "https://www.huddlehouse.com/locations/"),
    ("Hungry Howie's Pizza", "https://hungryhowies.hungerrush.com/Account/LogOn"),
    ("Hwy 55 Burgers Shakes & Fries", "https://hwy55.olo.com/"),
    ("IHOP", "https://www.ihop.com/en"),
    ("In-N-Out Burger", "https://www.in-n-out.com/"),
    ("Jack in the Box", "https://www.jackinthebox.com/location"),
    ("Jamba Juice", "https://www.jamba.com/"),
    ("Jason's Deli", "https://www.jasonsdeli.com/order-online"),
    ("Jersey Mike's Subs", "https://www.jerseymikes.com/order"),
    ("Jet's Pizza", "https://www.jetspizza.com/stores/"),
    ("Jimmy John's", "https://online.jimmyjohns.com/"),
    ("Joe's Crab Shack", "https://joescrabshack.alohaorderonline.com/Engage.aspx#/engage/ordering/menu"),
    ("Johnny Rockets", "https://order.johnnyrockets.com/"),
    ("Jollibee", "https://order.jollibeefoods.com/"),
    ("KFC", "https://www.kfc.com/menu"),
    ("Krystal", "https://www.krystal.com/locations"),
    ("Little Caesars", "https://littlecaesars.com/en-us/"),
    ("Logan's Roadhouse", "https://orders.logansroadhouse.com/"),
    ("Long John Silver's", "https://locations.ljsilvers.com/"),
    ("Maggiano's Little Italy", "https://orders.maggianos.com/"),
    ("Marco's Pizza", "https://www.marcos.com/locations/#start-order"),
    ("Marie Callender's", "https://www.mariecallenders.com/locations/"),
    ("McAlister's Deli", "https://www.mcalistersdeli.com/"),
    ("McDonald's", "https://www.mcdonalds.com/us/en-us.html"),
    ("MOD Pizza", "https://orders.modpizza.com/"),
    ("Moe's Southwest Grill", "https://order.moes.com/"),
    ("Newk's Eatery", "https://order.newks.com/"),
    ("O'Charley's", "https://order.ocharleys.com/?location=true"),
    ("Olive Garden", "https://www.olivegarden.com/order-online"),
    ("On the Border Mexican", "https://order.ontheborder.com/"),
    ("Outback Steakhouse", "https://order.outback.com/"),
    ("Panda Express", "https://www.pandaexpress.com/"),
    ("Panera Bread", "https://www.panerabread.com/en-us/home.html"),
    ("Papa John's Pizza", "https://www.papajohns.com/order/stores-near-me"),
    ("Papa Murphy's", "https://www.papamurphys.com/order/"),
    ("Pappadeaux Seafood Kitchen", "https://order.pappadeaux.com/"),
    ("Pei Wei Asian Diner", "https://order.peiwei.com/"),
    ("P.F. Chang's", "https://order.pfchangs.com/"),
    ("Pita Pit", "https://order.pitapitusa.com/"),
    ("Pizza Hut", "https://www.pizzahut.com/"),
    ("Planet Smoothie", "https://order.planetsmoothie.com/"),
    ("Pollo Campero", "https://order.campero.com/"),
    ("Ponderosa / Bonanza Steakhouse", "https://pon-bon.com/"),
    ("Popeyes", "https://www.popeyes.com/menu/"),
    ("Potbelly Sandwich Works", "https://www.potbelly.com/order/delivery"),
    ("Qdoba", "https://order.qdoba.com/"),
    ("Quiznos", "https://delivery.quiznos.com/"),
    ("Raising Cane's Chicken Fingers", "https://order.raisingcanes.com/"),
    ("Red Lobster", "https://www.redlobster.com/order"),
    ("Red Robin", "https://www.redrobin.com/order"),
    ("Romano's Macaroni Grill", "https://order.macaronigrill.com/"),
    ("Ruby Tuesday", "https://www.rubytuesday.com/order-now/"),
    ("Ruth's Chris Steak House", "https://order.ruthschris.com/"),
    ("Saladworks", "https://restaurants.saladworks.com/search"),
    ("Sbarro", "https://order.sbarro.com/"),
    ("Schlotzsky's", "https://order.schlotzskys.com/"),
    ("Shake Shack", "https://shakeshack.com/#/orderSetup/pickup"),
    ("Shakey's Pizza", "https://www.shakeys.com/restaurant-locations/"),
    ("Shane's Rib Shack", "https://www.shanesribshack.com/"),
    ("Shoney's", "https://www.shoneys.com/online-ordering-olo/"),
    ("Sizzler", "https://locations.sizzler.com/"),
    ("Smashburger", "https://order.smashburger.com/"),
    ("Smoothie King", "https://order.smoothieking.com/"),
    ("Sonic Drive-In", "https://order.sonicdrivein.com/"),
    ("Starbucks", "https://www.starbucks.com/menu"),
    ("Steak 'n Shake", "https://order.steaknshake.com/"),
    ("Subway", "https://order.subway.com/en-US/locator"),
    ("Sweetgreen", "https://order.sweetgreen.com/"),
    ("Taco Bell", "https://www.tacobell.com/food"),
    ("Taco John's", "https://order.tacojohns.com/"),
    ("Taco Mac", "https://order.tacomac.com/"),
    ("Taco Time", "https://order.tacotime.com/"),
    ("Texas Roadhouse", "https://www.texasroadhouse.com/order"),
    ("TGI Fridays", "https://order.tgifridays.com/"),
    ("The Capital Grille", "https://www.thecapitalgrille.com/menu"),
    ("The Cheesecake Factory", "https://www.thecheesecakefactory.com/locations"),
    ("The Halal Guys", "https://order.thehalalguys.com/"),
    ("The Habit Burger Grill", "https://order.habitburger.com/"),
    ("The Melting Pot", "https://www.meltingpot.com/"),
    ("The Original Pancake House", "https://www.originalpancakehouse.com/"),
    ("Tim Hortons", "https://www.timhortons.com/store-locator/service-mode"),
    ("Tropical Smoothie Cafe", "https://order.tropicalsmoothiecafe.com/"),
    ("Twin Peaks", "https://twinpeaksrestaurant.olo.com/"),
    ("Waffle House", "https://www.wafflehouse.com/"),
    ("Wayback Burgers", "https://wayback.order.online/business/wayback-burgers-12019/"),
    ("Wendy's", "https://order.wendys.com/categories?site=menu&delivery=true"),
    ("Wetzel's Pretzels", "https://order.wetzels.com/"),
    ("Whataburger", "https://whataburger.com/home"),
    ("Which Wich?", "https://www.whichwich.com/locations/"),
    ("White Castle", "https://order.whitecastle.com/OrderNow/location/menu"),
    ("Wienerschnitzel", "https://order.wienerschnitzel.com/"),
    ("Wingstop", "https://www.wingstop.com/order/action/delivery"),
    ("WingStreet", "https://www.pizzahut.com/menu/wings"),
    ("Zaxby's", "https://www.zaxbys.com/menu"),
)